version : "3"
services :
        node1 :
                image : hub.c.163.com/haoyoyo/etcd:v3.3.6
                volumes :
                        - "./node1-data:/etcd-data"
                expose :
                        - 2379
                        - 2380
                networks :
                    etcd_net :
                        ipv4_address : 172.14.238.100
                environment :
                        - ETCDCTL_API=3
                command :
                        - /usr/local/bin/etcd
                        - --data-dir=/etcd-data
                        - --name
                        - node1
                        - --initial-advertise-peer-urls
                        - http://172.14.238.100:2380
                        - --listen-peer-urls
                        - http://0.0.0.0:2380
                        - --advertise-client-urls
                        - http://172.14.238.100:2379
                        - --listen-client-urls
                        - http://0.0.0.0:2379
                        - --initial-cluster
                        - node1=http://172.14.238.100:2380,node2=http://172.14.238.101:2380,node3=http://172.14.238.102:2380
                        - --initial-cluster-state
                        - new
                        - --initial-cluster-token
                        - docker-etcd-cluster
        node2 :
                image : hub.c.163.com/haoyoyo/etcd:v3.3.6
                volumes :
                        - "./node2-data:/etcd-data"
                expose :
                        - 2379
                        - 2380
                networks :
                    etcd_net :
                        ipv4_address : 172.14.238.101
                environment :
                        - ETCDCTL_API=3
                command :
                        - /usr/local/bin/etcd
                        - --data-dir=/etcd-data
                        - --name
                        - node2
                        - --initial-advertise-peer-urls
                        - http://172.14.238.101:2380
                        - --listen-peer-urls
                        - http://0.0.0.0:2380
                        - --advertise-client-urls
                        - http://172.14.238.101:2379
                        - --listen-client-urls
                        - http://0.0.0.0:2379
                        - --initial-cluster
                        - node1=http://172.14.238.100:2380,node2=http://172.14.238.101:2380,node3=http://172.14.238.102:2380
                        - --initial-cluster-state
                        - new
                        - --initial-cluster-token
                        - docker-etcd-cluster
        node3 :
                image : hub.c.163.com/haoyoyo/etcd:v3.3.6
                volumes :
                        - "./node3-data:/etcd-data"
                expose :
                        - 2379
                        - 2380
                networks :
                    etcd_net :
                        ipv4_address : 172.14.238.102
                environment :
                        - ETCDCTL_API=3
                command :
                        - /usr/local/bin/etcd
                        - --data-dir=/etcd-data
                        - --name
                        - node3
                        - --initial-advertise-peer-urls
                        - http://172.14.238.102:2380
                        - --listen-peer-urls
                        - http://0.0.0.0:2380
                        - --advertise-client-urls
                        - http://172.14.238.102:2379
                        - --listen-client-urls
                        - http://0.0.0.0:2379
                        - --initial-cluster
                        - node1=http://172.14.238.100:2380,node2=http://172.14.238.101:2380,node3=http://172.14.238.102:2380
                        - --initial-cluster-state
                        - new
                        - --initial-cluster-token
                        - docker-etcd-cluster
networks :
        etcd_net :
                driver : bridge
                ipam :
                        driver : default
                        config :
                        - subnet : 172.14.238.0/24