version : "3"
services :
        mysql-master :
                image : mysql:5.6
                volumes :
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                        - ./my-master.cnf:/etc/mysql/my.cnf
                        - ./mysql-data-master:/var/lib/mysql
                environment :
                        - MYSQL_ROOT_PASSWORD=123456
                ports :
                        - 3307:3306
        mysql-slave :
                image : mysql:5.6
                volumes :
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                        - ./my-slave.cnf:/etc/mysql/my.cnf
                        - ./mysql-data-slave:/var/lib/mysql
                environment :
                        - MYSQL_ROOT_PASSWORD=123456
                ports :
                        - 3308:3306