version : "3"
services :
        nsqlookupd-A :
                image : nsqio/nsq
                command : /nsqlookupd
                ports :
                        - "4160"
                        - "24161:4161"
        nsqlookupd-B :
                image : nsqio/nsq
                command : /nsqlookupd
                ports :
                        - "4160"
                        - "34161:4161"
        nsqd-A :
                image : nsqio/nsq
                command : /nsqd --lookupd-tcp-address=nsqlookupd-A:4160,nsqlookupd-B:4160 --data-path=/data
                volumes :
                        - ./nsqd-A-data:/data
                depends_on :
                        - nsqlookupd-A
                        - nsqlookupd-B
                ports :
                        - "24150:4150"
                        - "4151"
        nsqd-B :
                image : nsqio/nsq
                command : /nsqd --lookupd-tcp-address=nsqlookupd-A:4160,nsqlookupd-B:4160 --data-path=/data
                volumes :
                        - ./nsqd-B-data:/data
                depends_on :
                        - nsqlookupd-A
                        - nsqlookupd-B
                ports :
                        - "34150:4150"
                        - "4151"
        nsqd-C :
                image : nsqio/nsq
                command : /nsqd --lookupd-tcp-address=nsqlookupd-A:4160,nsqlookupd-B:4160 --data-path=/data
                volumes :
                        - ./nsqd-C-data:/data
                depends_on :
                        - nsqlookupd-A
                        - nsqlookupd-B
                ports :
                        - "44150:4150"
                        - "4151"
        nsqadmin :
                image : nsqio/nsq
                command : /nsqadmin --lookupd-http-address=nsqlookupd-A:4161,nsqlookupd-B:4161
                depends_on :
                        - nsqlookupd-A
                        - nsqlookupd-B
                ports :
                        - "4171:4171"