# https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docker.html
# https://www.elastic.co/guide/cn/kibana/current/docker.html
version : "2.2"
services :
        elasticsearch1 :
                image : docker.elastic.co/elasticsearch/elasticsearch:6.3.2
                container_name : elasticsearch1
                environment :
                        - cluster.name=docker-cluster
                        - bootstrap.memory_lock=true
                        - node.name=elasticsearch1
                        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
                volumes:
                        - esdata1:/usr/share/elasticsearch/data
                networks:
                        - esnet
                ports :
                        - 9200:9200
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
        elasticsearch2 :
                image : docker.elastic.co/elasticsearch/elasticsearch:6.3.2
                container_name : elasticsearch2
                environment :
                        - cluster.name=docker-cluster
                        - node.name=elasticsearch2
                        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
                        - "discovery.zen.ping.unicast.hosts=elasticsearch1"
                volumes :
                        - esdata2:/usr/share/elasticsearch/data
                networks:
                        - esnet
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
        kibana:
                image: docker.elastic.co/kibana/kibana:6.3.2
                container_name : kibana
                environment:
                        ELASTICSEARCH_URL: http://elasticsearch1:9200
                ports:
                        - 5601:5601
                depends_on:
                        - elasticsearch1
                        - elasticsearch2
                networks:
                        - esnet
volumes:
        esdata1:
                driver: local
        esdata2:
                driver: local
networks:
        esnet:
                driver: bridge
