version : "3"
services :
        mysql :
                image : mysql:5.6
                volumes :
                        - ./my.cnf:/etc/mysql/my.cnf
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                        - ./mysql-data:/data/mysql
                environment :
                        - MYSQL_ROOT_PASSWORD=123456
                ports :
                        - 3307:3306